# Generated by Django 5.2.1 on 2025-05-17 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_image_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_images", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
