# Generated by Django 5.2.1 on 2025-05-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_image_likes_alter_image_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
